"""empty message

Revision ID: 34765d6575fd
Revises: c2562ee3d15d
Create Date: 2024-11-28 10:02:35.945349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34765d6575fd'
down_revision = 'c2562ee3d15d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.Column('description', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
